# Generated by Django 3.2.5 on 2021-07-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('tipo_do_combustivel', models.CharField(max_length=100, verbose_name='Tipo do combustivel')),
                ('portas', models.CharField(max_length=100)),
                ('motor', models.CharField(max_length=100)),
                ('tipo_da_carroceria', models.CharField(max_length=100, verbose_name='Tipo da carroceria')),
                ('km', models.CharField(max_length=100, verbose_name='Quilômetros')),
            ],
        ),
    ]
