# Generated by Django 3.2.5 on 2021-07-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='transmissao',
            field=models.CharField(default='', max_length=100, verbose_name='Transmissão'),
            preserve_default=False,
        ),
    ]
