# Generated by Django 3.2.5 on 2021-07-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_carro_transmissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='cor',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
